# 七牛云对象储存服务配置
tumo.qiniu.ak=7fdGybOPVO_zNnpeA9wLO__IASW8bc1XpZevZO3y
tumo.qiniu.sk=dD5QoqAJTbZCnda19WtwxH9bdoNAdPfvlTPu032C
tumo.qiniu.bn=blog20250110
# 请按照http://xxx/ 格式
tumo.qiniu.url=http://spvpwxtru.hn-bkt.clouddn.com

# Shiro 配置
tumo.shiro.session_timeout=3600
tumo.shiro.cookie_timeout=86400
tumo.shiro.anon_url=\
  /api/login,/api/logout,/api/register,/api/user/info/*,\
  /api/article/list/**,/api/article/*,/api/comment/**,/api/link/**,\
  /swagger-ui.html,/api/swagger-ui.html,/swagger/**,/swagger-ui/**,/swagger-resources/**,/v2/**,/v3/**,/webjars/**,/configuration/**,/doc.html
tumo.shiro.login_url=/login
tumo.shiro.success_url=/system
tumo.shiro.logout_url=/logout
tumo.shiro.cipher_key=tycoding

# Swagger2 配置
tumo.swagger.base_package=cn.menghuan.blog.controller
tumo.swagger.title=Tumo Blog Api
tumo.swagger.description=Tumo Blog Api Document
tumo.swagger.name=TyCoding
tumo.swagger.url=http://localhost:8080/swagger-ui.html
tumo.swagger.email=tumo@163.com
tumo.swagger.version=v2.0
